//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanF2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string RutU { get; set; }
        public string Clave { get; set; }
        public string Rol { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Bodeguero Bodeguero { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
