//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmericanF2.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Folio { get; set; }
        public Nullable<int> Producto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Hora { get; set; }
        public string NombreEmpresa { get; set; }
        public string Total { get; set; }
        public string Vendedor { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Producto Producto1 { get; set; }
        public virtual Vendedor Vendedor1 { get; set; }
    }
}
